### ISSUE TITLE
Require resolves to the sibling node_modules if lookup failed in the given dir.

### ISSUE THREAD

**Issue by inikulin** [sindresorhus/resolve-from#1]
Hi! :cow: 

I have the following dir structure:
`some-dir/node_modules/mah-package`
`some-dir/mah-project/resolve-from-here`

If I run 
```js
resolveFrom('resolve-from-here', 'mah-package')
```

it resolves to `some-dir/node_modules/mah-package`. This can be avoided by keeping only subdirs of the given dir here: https://github.com/sindresorhus/resolve-from/blob/master/index.js#L18

I can issue a PR if you confirm that it's not expected behavior.

**Comment by sindresorhus** [comment]
That's how the Node.js module resolution works.

https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders

**Comment by inikulin** [comment]
> That's how the Node.js module resolution works.

Thanks, I know it. I've had wrong impression that this module tries to find module **exactly** in the specified dir.
