### ISSUE TITLE
Support for extensions other than `.js`

### ISSUE THREAD

**Issue by NickHeiner** [sindresorhus/resolve-from#15]
I work with TS. I'd like to use `resolve-from` to resolve paths to `.ts` files. However, this module only considers `.js` files. Would you consider adding a configurable set of extensions, like what we can do with Webpack?

**Comment by sindresorhus** [comment]
That's unfortunately not possible.  This module uses internal Node.js machinery to do its thing and Node.js can't resolve `.ts` files natively. However, if you add `.ts` as a require extension, it should just work with this package too.

https://gist.github.com/jamestalmage/df922691475cff66c7e6

What problem are you trying to solve though? Maybe there's a better way. Why do you need to resolve `.ts` files directly?

**Comment by NickHeiner** [comment]
Adding `.ts` as a require extension should do it for me. Thanks.

I need to resolve `ts` files directly because I'm writing a lint rule that determines what an `import`/`require` will resolve to. It runs before TS compilation, so there are no JS files available to resolve at that time.

**Comment by NickHeiner** [comment]
I confirmed that adding `.ts` as a require extension solves my problem. NICE.
