### ISSUE TITLE
Add Yarn PnP support?

### ISSUE THREAD

**Issue by akrawitz** [sindresorhus/resolve-from#16]
Yarn v2 is moving away from node_modules to use Plug'n'Play instead. If I understand this all correctly, it would be very helpful if this package supported PnP-based resolution in addition to the traditional node_modules approach, since many other packages rely on this package for resolution as an alternative to `require.resolve`. For reference:
[Yarn Plug'n'Play](https://yarnpkg.com/features/pnp)

Thanks for all of your amazing open source work!

**Comment by sindresorhus** [comment]
Sorry, I have no intention of supporting Yarn PnP. It's up to Yarn to support how the ecosystem works, not the other way around. I'd recommend opening an issue on https://github.com/yarnpkg/berry.

**Comment by kachkaev** [comment]
Facing this problem in https://github.com/vercel/vercel/discussions/4910. A solution via upgrading this package would be ideal, but if it’s against the future vision, I guess the logic would need to include some workaround. Does anyone have any examples? Perhaps, there exists a package like `resolve-from-but-also-support-yarn-pnp`?

**Comment by merceyz** [comment]
This package already supports PnP, it's using `Module._resolveFilename` which supports PnP, so there are no changes required here.

**Comment by kachkaev** [comment]
@merceyz my knowledge of the topic is quite modest, so what you’re saying may well be true. What are your thoughts on https://github.com/vercel/vercel/discussions/4910#discussioncomment-59838? This is what points the investigation towards this issue.

**Comment by merceyz** [comment]
Lets take that in https://github.com/yarnpkg/berry/issues/2031, no need to bother Sindre with this
