### ISSUE TITLE
Resolving require('module') for webpack

### ISSUE THREAD

**Issue by saiichihashimoto** [sindresorhus/resolve-from#2]
[Mongoose](https://github.com/Automattic/mongoose) is meant to [work in the browser](http://mongoosejs.com/docs/browser.html). However, including their module [in](https://github.com/Automattic/mongoose/issues/3713) [webpack](https://github.com/webpack/webpack/issues/2566) [is](https://github.com/webpack/webpack/issues/1040) [broken](https://github.com/Automattic/mongoose/issues/3578). Determined to resolve this for them, I did a bit of digging. `npm ls` in a package using mongoose reveals:

```
├─┬ mongoose@4.6.0
│ ├── async@1.5.2
│ ├── bson@0.5.4
│ ├── hooks-fixed@1.2.0
│ ├── kareem@1.1.3
│ ├─┬ mongodb@2.2.9
│ │ ├─┬ mongodb-core@2.0.11
│ │ │ └─┬ require_optional@1.0.0
│ │ │   ├── resolve-from@2.0.0        # Here's you!
│ │ │   └── semver@5.3.0
│ │ └─┬ readable-stream@2.1.5
│ │   ├── buffer-shims@1.0.0
│ │   └── isarray@1.0.0
│ ├── mpath@0.2.1
│ ├── mpromise@0.5.5
│ ├─┬ mquery@1.11.0
│ │ ├── bluebird@2.10.2
│ │ └── sliced@0.0.5
│ ├── ms@0.7.1
│ ├── muri@1.1.0
│ ├── regexp-clone@0.0.1
│ └── sliced@1.0.1
```

The error the webpack build is outputting is:

```
ERROR in ./~/require_optional/~/resolve-from/index.js
Module not found: Error: Cannot resolve module 'module' in /<my project>/node_modules/require_optional/node_modules/resolve-from
 @ ./~/require_optional/~/resolve-from/index.js 3:13-30
```

The dependency it is referring to is in [this package](https://github.com/sindresorhus/resolve-from/blob/3796248746d91d17ab894f55b1d708e35c5b2923/index.js#L3):

```js
'use strict';
var path = require('path');
var Module = require('module');  // Here's the problem!!!

// ...
```

I'm sure solving their build will take more than resolving this and it's understandable if you're not supporting webpack. This is just an investigation that's piqued my interest.

So, two questions/requests:

1. `module` is not a dependency of this package. Where is it coming from? What is this?
2. Is there a different solution that would work in both cases? Is it out of the scope of this package to have a `.web.js` implementation of this to resolve the issue for webpack?

**Comment by sindresorhus** [comment]
1. It's a Node.js built-in.
2. Report any problems with modules on the Webpack issue tracker. This works on Node.js, so it's a bug that Webpack doesn't perfectly emulate it.

**Comment by TeodorKolev** [comment]
Same here

**Comment by Shaunwei** [comment]
same here
