### ISSUE TITLE
Use the real path for resolving dependencies

### ISSUE THREAD

**Issue by zkochan** [sindresorhus/resolve-from#6]
I created a similar issue at the [resolve](https://github.com/substack/node-resolve/issues/130) repo.

Node uses the real path of modules (except when executed with `--preserve-symlinks`) to resolve dependencies. That is why [pnpm](https://github.com/pnpm/pnpm)'s [symlinked `node_modules`](https://github.com/pnpm/pnpm/blob/master/docs/symlinked-node-modules-structure.md) work fine with Node applications.

However, `resolve-from` does not use the real path of modules to resolve dependencies. As a consequence, toolings that use `resolve-from` break on projects that use pnpm. These are issues related to `resolve` but I checked them with `resolve-from` and they fail with it as well: https://github.com/pnpm/pnpm/issues/857, https://github.com/pnpm/pnpm/issues/801

Would you accept a pull request to change the behavior of `resolve-from` to work the way Node does? It won't change anything for projects that use npm/Yarn because they don't leverage symlinks but it would be a **huge** help for the pnpm community!

**Comment by sindresorhus** [comment]
Sure
